version: '2'
services:
    test-app:
        image: test
        external_links:
            - test-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    test-mysql:
        extends:
            file: mysql.yml
            service: test-mysql
